### ISSUE TITLE
안녕하세요 :)

### ISSUE THREAD

**Issue by cometkim** [josephk96/mattermost-korean-guide#1]
안녕하세요. 저는 Mattermost 의 한국어 첫 50% 기여자이자 i18n -ko 채널장이자 코어 커미터인 김혜성이라고 합니다.

오랫동안 저나 커뮤니티의 한국어 기여가 뜸했기에.. 이런 활동이 있는게 매우 감사하게 느껴집니다. 다만 조금 우려되는 부분이 있어 이렇게 이슈남깁니다.

1. 맥락에 따른 단어 선택의 제한

제가 처음 번역을 만들면서 느꼈던 Mattermost 의 GUI 워딩은... "매우 맥락에 의존적"이라는 것입니다. (그리고 그게 사용자에게 더 친숙한 UI를 제공하는 방법이기에 점점 더 그렇게 되어갈겁니다.)

따라서 저도 비슷하게 테이블을 만들어 공유하려는 시도를 했습니다만... (참고: https://community.mattermost.com/core/pl/nxf8s6w5b3b68x45hdm5ssgwyr)

저 스스로도 잘 지켜지지 못하고 때로는 딱딱한 번역을 만들게 되는 원인이 되기도 했습니다.

지금은 Alpha 단계인 만큼 번역의 질보다 양 이 우선되는 단계라 크게 왈가왈부 할 마음은 없으나, 가이드라인을 제시하기에도 이른 단계가 아닐까 합니다.

(제시한다고 하더라도 "용어집" 보다는 "번역 사례 모음" 정도가 적당한 역할이라고 봅니다)

2. 다소 의미와는 떨어지는 직역

예를 들면: `third party: 제삼자`, `SAML Assertion: SAML 주장`

이러한 직역은 맥락에 따라 원래의 의미를 완전히 잃어버릴 수도 있는 위험한 번역입니다. 전문 용어 계열은 대부분 번역어도 음차 그대로 사용되는 경우가 많기 때문에 실제로 업계에서 "널리 쓰이는" 대체어가 있지 않다면 섣불리 직역하지 않았으면 합니다.

**Comment by josephk96** [comment]
안녕하세요, 저희 프로젝트에 관심을 가져 주셔서 감사합니다. 이 프로젝트에 있는 용어집이나 스타일 가이드에 대한 의견 있으시다면 언제든지 PR해 주세요.

감사합니다.
